name: Execute Experiment

on: workflow_dispatch

defaults:
  run:
    shell: bash

jobs:
  execution-of-automated-research-methods:
    name: Execution of automated research methods
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run experiment
        run: python src/main.py > output/output.log 2> output/error.log

      - uses: actions/upload-artifact@v4
        with:
          name: output
          path: output/output.txt
          retention-days: 1

      - uses: actions/upload-artifact@v4
        with:
            name: error
            path: output/error.txt
            retention-days: 1
